create database motos;
use motos;


create table USUARIOS(
  CODIGO DOUBLE primary key not null,
  NOMBRE varchar(50),
  APELLIDOS varchar(70)
);

create table VEICULOS(
  PLACA VARCHAR(10) PRIMARY KEY NOT NULL,
  MARCA VARCHAR(20),
  COLOR VARCHAR(20),
  FOTO LONGBLOB,
  PROPIETARIO DOUBLE,

  FOREIGN KEY (PROPIETARIO) REFERENCES USUARIOS(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP DATABASE motos